package net.lesscoding.action;

import com.intellij.notification.NotificationGroup;
import com.intellij.notification.Notifications;
import com.intellij.openapi.actionSystem.AnAction;
import com.intellij.openapi.actionSystem.AnActionEvent;

/**
 * @author eleven
 * @date 2021/8/17 16:13
 * @apiNote
 */
public class MainAction extends AnAction {

    @Override
    public void actionPerformed(AnActionEvent e) {
        System.out.println("Generated By LessCoding");
    }
}
